### ISSUE TITLE
Panic: called glDebugMessageCallbackKHR but it was not loaded.

### ISSUE THREAD

**Issue by inflation** [notgull/piet-hardware#4]
macOS 13.2.1 Ventura 

```bash
cargo run --example basics

Config: Cgl(Config { inner: Config { id: NSOpenGLPixelFormat { __inner: <NSOpenGLPixelFormat: 0x600003fb4690> } } })
Color Buffer Type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
Float Pixels: false
Alpha Size: 8
Depth Size: 32
Stencil Size: 8
Samples: 0
SRGB Capable: true
Supports Transparency: Some(false)
Hardware Accelerated: true
Config Surface Types: WINDOW
Api: OPENGL
thread 'main' panicked at 'called glDebugMessageCallbackKHR but it was not loaded.', /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glow-0.12.1/src/gl46.rs:4571:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/core/src/panicking.rs:64:14
   2: glow::gl46::go_panic_because_fn_not_loaded
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glow-0.12.1/src/gl46.rs:4571:5
   3: glow::gl46::call_atomic_ptr_2arg
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glow-0.12.1/src/gl46.rs:4653:17
   4: glow::gl46::struct_commands::GlFns::DebugMessageCallbackKHR
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glow-0.12.1/src/gl46.rs:10690:23
   5: <glow::native::Context as glow::HasContext>::debug_message_callback
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glow-0.12.1/src/native.rs:2560:13
   6: basics::util::with_renderer::{{closure}}::{{closure}}
             at ./examples/util/setup_context.rs:173:29
   7: core::option::Option<T>::get_or_insert_with
             at /rustc/7820b62d20bc548096d4632a3487987308cb4b5d/library/core/src/option.rs:1712:49
   8: basics::util::with_renderer::{{closure}}
             at ./examples/util/setup_context.rs:162:21
   9: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.2/src/platform_impl/macos/app_state.rs:96:17
  10: winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.2/src/platform_impl/macos/app_state.rs:70:13
  11: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.2/src/platform_impl/macos/app_state.rs:91:9
  12: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.2/src/platform_impl/macos/app_state.rs:199:21
  13: winit::platform_impl::platform::app_state::AppState::launched
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.2/src/platform_impl/macos/app_state.rs:302:9
  14: winit::platform_impl::platform::app_delegate::ApplicationDelegate::did_finish_launching
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.2/src/platform_impl/macos/app_delegate.rs:42:13
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
libc++abi: terminating with uncaught foreign exception
fish: Job 1, 'RUST_BACKTRACE=1 cargo run --ex…' terminated by signal SIGABRT (Abort)
```

**Comment by notgull** [comment]
Does CGL not support debug logging? Weird. If you comment out these lines, does it work?

https://github.com/notgull/piet-hardware/blob/f3473e3b8373de69c765386a6bbb9a01aed6cd72/crates/piet-glow/examples/util/setup_context.rs#L169-L176

**Comment by notgull** [comment]
Mhmm, looks like GL on Mac is a bit of a harsher story than on Linux. I don't have a Mac personally, so it would be difficult for me to test this. Let me look into this.

**Comment by inflation** [comment]
Yeah, Apple deprecated OpenGL and limiting support to 4.1 which is also buggy and poorly supported.

**Comment by inflation** [comment]
Still happens, I'm on latest commit

```bash
Config: Cgl(Config { inner: Config { id: NSOpenGLPixelFormat { __inner: <NSOpenGLPixelFormat: 0x600003b980a0> } } })
Color Buffer Type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
Float Pixels: false
Alpha Size: 8
Depth Size: 32
Stencil Size: 8
Samples: 0
SRGB Capable: true
Supports Transparency: Some(false)
Hardware Accelerated: true
Config Surface Types: WINDOW
Api: OPENGL
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackendError(GlError("ERROR: 0:43: Invalid call of undeclared identifier 'texture2D'\nERROR: 0:44: Use of undeclared identifier 'textureColor'\nERROR: 0:46: Invalid call of undeclared identifier 'texture2D'\nERROR: 0:47: Use of undeclared identifier 'mainColor'\nERROR: 0:47: Use of undeclared identifier 'maskColor'\nERROR: 0:49: Use of undeclared identifier 'gl_FragColor'\nERROR: 0:49: Use of undeclared identifier 'finalColor'\n"))', crates/piet-glow/examples/util/setup_context.rs:255:73
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb80ff132a0e9aa71529b701427e4e6c243b58df/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/cb80ff132a0e9aa71529b701427e4e6c243b58df/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cb80ff132a0e9aa71529b701427e4e6c243b58df/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/cb80ff132a0e9aa71529b701427e4e6c243b58df/library/core/src/result.rs:1076:23
   4: basics::util::glutin_impl::GlutinSetup::run::{{closure}}::{{closure}}
             at ./crates/piet-glow/examples/util/setup_context.rs:255:38
   5: core::option::Option<T>::get_or_insert_with
             at /rustc/cb80ff132a0e9aa71529b701427e4e6c243b58df/library/core/src/option.rs:1665:26
   6: basics::util::glutin_impl::GlutinSetup::run::{{closure}}
             at ./crates/piet-glow/examples/util/setup_context.rs:251:25
   7: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/macos/app_state.rs:96:17
   8: winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/macos/app_state.rs:70:13
   9: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/macos/app_state.rs:91:9
  10: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/macos/app_state.rs:199:21
  11: winit::platform_impl::platform::app_state::AppState::launched
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/macos/app_state.rs:302:9
  12: winit::platform_impl::platform::app_delegate::ApplicationDelegate::did_finish_launching
             at /Users/inflation/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/macos/app_delegate.rs:42:13
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
libc++abi: terminating due to uncaught foreign exception
fish: Job 1, 'RUST_BACKTRACE=1 cargo run --ex…' terminated by signal SIGABRT (Abort)
```
